#!/usr/bin/python

import socket

def conectar_smtp(ip):
    try:
        smtp = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        smtp.connect((ip, 25))
        return smtp
    except Exception as e:
        print(f"Erro ao conectar ao serviço SMTP: {e}")
        return None

def receber_resposta(smtp):
    try:
        resposta = smtp.recv(1024)
        return resposta.decode()
    except Exception as e:
        print(f"Erro ao receber resposta: {e}")
        return None

def verificar_usuario(smtp, usuario):
    try:
        smtp.send(str.encode(f"VRFY {usuario}\r\n"))
        resposta = smtp.recv(1024)
        return resposta.decode()
    except Exception as e:
        print(f"Erro ao verificar usuário: {e}")
        return None

def main():
    print("Bem vindo ao Script de Enumeração SMTP")
    
    ip = input("Digite o IP a ser verificado: ")
    
    print("Conectando ao serviço...")
    smtp = conectar_smtp(ip)
    
    if smtp:
        resposta = receber_resposta(smtp)
        if resposta:
            print(f"Resposta do servidor: {resposta}")
        
        print("Verificando usuário root...")
        resposta_usuario = verificar_usuario(smtp, "root")
        if resposta_usuario:
            print(f"Resposta ao verificar usuário root: {resposta_usuario}")
        
        smtp.close()
    else:
        print("Não foi possível conectar ao serviço SMTP.")

if __name__ == "__main__":
    main()
